volumes:
  relay_data: {}
services:
  relay:
    container_name: haven
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "relay_data:/app/db"
      # - "./templates/index.html:${INDEX_PATH}"
      # - "./templates/static:${STATIC_PATH}"
    ports:
      - "3355:3355"